#! /usr/bin/env zsh

autoload zcalc

#
# ::: Utilities ::
#
function next; [[ -z "$1" ]] && echo -n $(zcalc -e "$(<&0) +  1") || echo -n $(zcalc -e "$1 + 1")
function add;  [[ -z "$2" ]] && echo -n $(zcalc -e "$(<&0) + $1") || echo -n $(zcalc -e "$1 + $2")
function sub;  [[ -z "$2" ]] && echo -n $(zcalc -e "$(<&0) - $1") || echo -n $(zcalc -e "$1 - $2")
function div;  [[ -z "$2" ]] && echo -n $(zcalc -e "$(<&0) / $1") || echo -n $(zcalc -e "$1 / $2")

#
# ::: Main :::
#
function main {
  local -a params=("$@")
  local -a options=(${params[1, -1]})

  local page_title=${options[$(echo $options[(i)-p:t] | next)]}
  local page_number=${options[$(echo $options[(i)-p:n] | next)]}
  local page_width=${options[$(echo $options[(i)-p:w] | next)]}
  local page_height=${options[$(echo $options[(i)-p:h] | next)]}
  local text_width=${options[$(echo $options[(i)-t:w] | next)]}
  local text_height=${options[$(echo $options[(i)-t:h] | next)]}

  local margin_top=$(sub $page_height $text_height | div 2.0)
  local margin_right=$(sub $page_width $text_width | div 2.0 | add $text_width)
  local margin_bottom=$(sub $page_height $text_height | div 2.0 | add $text_height)
  local margin_left=$(sub $page_width $text_width | div 2.0)

  local cut_top=$(sub $margin_top 2.0)
  local cut_right=$(add $margin_right 2.0)
  local cut_bottom=$(add $margin_bottom 2.0)
  local cut_left=$(sub $margin_left 2.0)

  printf "%s, с. %d\n  Страница\n  ----\n  Ширина: %6.2f мм\n  Высота: %6.2f мм\n  ----\n  Текст\n  ----\n  Ширина: %6.2f мм\n  Высота: %6.2f мм\n  ----\n  Границы текст\n  ----\n  Верхняя: %6.2f мм\n  Правая: %7.2f мм\n  Нижняя: %7.2f мм\n  Левая: %8.2f мм\n  ----\n  Границы обрезка\n  ----\n  Верхняя: %6.2f мм\n  Правая: %7.2f мм\n  Нижняя: %7.2f мм\n  Левая: %8.2f мм\n" \
    $page_title \
    $page_number \
    $page_width \
    $page_height \
    $text_width \
    $text_height \
    $margin_top \
    $margin_right \
    $margin_bottom \
    $margin_left \
    $cut_top \
    $cut_right \
    $cut_bottom \
    $cut_left \
      | tee >(xclip -selection 'clipboard' -i)
}

main "$@"

# vim: set textwidth=80 colorcolumn=80:
